### ISSUE TITLE
Difference between conditions

### ISSUE THREAD

**Issue by AmirSavand** [AmirSavand/royale-plus#44]
```python
if user:
```
or
```python
if user is not None:
```

@Alir3z4 aren't they the same? I copied a piece of code and it used the 2nd way, Can I use the first way? Shorter and cleaner.

Where it's used:

```python
    def get_queryset(self):
        queryset = super(DeckViewSet, self).get_queryset()
        user = self.request.query_params.get('user', None)

        if user is not None:
            queryset = queryset.filter(user__username=user)

        return queryset
```

**Comment by Alir3z4** [comment]
The thing is: 
* if `user = ''` then `if user` => `False
* if `user = 0` then `if user` => `False`

So you should be user if you're actually fine with with those cases.
You should be fine with using the first one.
Because in case of second option you should take care of `if user not in [None, 0 , '']`
